version: '3.1'

services:

    mongo:
        image: mongo:3.4.21
        container_name: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: jccBjJSml7g
        volumes:
          - ../data:/data/db

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - 8090:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: jccBjJSml7g
        depends_on:
          - mongo
        links:
          - mongo
